// Generated by scripts/generate-schema-types.ts from scenario-1.3.0.schema.json.
// Do not edit this file directly.
export const SCHEMA_VERSION = "1.3.0" as const;

export interface Point {
  x: number;
  y: number;
}

export interface Rectangle {
  id: string;
  x: number;
  y: number;
  width: number;
  height: number;
  blocksVision?: boolean;
  blocksMovement?: boolean;
}

export interface ExitZone {
  id: string;
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface SquadSpec {
  id: string;
  side: string;
  leaderId?: string;
  initialCohesion: number;
}

export interface ActorSpec {
  id: string;
  side: string;
  position: Point;
  facingDegrees?: number;
  visionRange?: number;
  visionArcDegrees?: number;
  movementSpeed?: number;
  massKg?: number;
  radiusM?: number;
  skill?: number;
  balance?: number;
  guard?: number;
  mobility?: number;
  surprise?: number;
  reachM?: number;
  protection?: number;
  stance?: "neutral" | "mobile" | "guarded" | "committed";
  readiness: number;
  stamina: number;
  resolve: number;
  fear?: number;
  aggression?: number;
  squadId?: string;
  leader?: boolean;
  humanIntent?: "observe" | "communicate" | "reposition" | "protect" | "withdraw" | "ready-tool" | "commit" | "aid-ally" | "rally" | "wait";
  threatened?: boolean;
  policyId?: "safety-first" | "random-valid" | "sportive" | "chen-inspired" | "human-intent";
  role?: string;
  attention?: number;
  hearingRangeM?: number;
  soundSignature?: number;
  awareness?: number;
  tags?: string[];
  tool?: AbstractToolSpec;
  humanTargetActorId?: string;
  humanTargetPoint?: Point;
}

export interface PhysicsRules {
  enabled?: boolean;
  interruptMargin?: number;
  tempoNoise?: number;
  contactNoise?: number;
  recoveryPerPulse?: number;
  impairmentRecoveryPerPulse?: number;
  separationScaleM?: number;
  neutralizationThreshold?: number;
}

export interface MoraleRules {
  enabled?: boolean;
  shockRadiusM?: number;
  shockFalloff?: number;
  allyShockScale?: number;
  leaderResistance?: number;
  cascadeDepth?: number;
  perPulseCap?: number;
  shakenThreshold?: number;
  frozenThreshold?: number;
  routeThreshold?: number;
  recoverThreshold?: number;
  recoveryPerPulse?: number;
}

export interface ObjectiveSpec {
  id: string;
  kind: "protect-side" | "neutralize-side" | "separation" | "evacuate-side";
  side?: string;
  actorIds?: string[];
  minimumDistanceM?: number;
}

export interface TerminalConditionSpec {
  kind: "threat-ended" | "side-neutralized" | "side-routed" | "objective-complete";
  side?: string;
  objectiveId?: string;
}

export interface NavigationArea {
  id: string;
  x: number;
  y: number;
  width: number;
  height: number;
}

export interface EnvironmentZone {
  id: string;
  kind: "cover" | "light" | "noise";
  x: number;
  y: number;
  width: number;
  height: number;
  value: number;
}

export interface EnvironmentSpec {
  ambientLight?: number;
  ambientNoise?: number;
  visibilityScale?: number;
}

export interface ScheduledEventSpec {
  id: string;
  tick: number;
  kind: "threat-state" | "environment";
  active?: boolean;
  ambientLight?: number;
  ambientNoise?: number;
  visibilityScale?: number;
}

export interface AbstractToolSpec {
  id: string;
  class: "none" | "barrier" | "signal" | "short-reach" | "long-reach";
  reachM: number;
  readiness: number;
  concealment: number;
  durability: number;
  defensiveUtility: number;
  intimidation: number;
}

export interface EngagementRules {
  minimumSeverity?: number;
  minimumImmediacy?: number;
  requireThreatenedParty?: boolean;
  permitCommit?: boolean;
  permitProtect?: boolean;
  permitWithdrawal?: boolean;
}

export interface ScenarioSpec {
  schemaVersion: "1.3.0";
  id: string;
  name: string;
  seed: number;
  pulseMs: 100;
  maxTicks: number;
  map: {
    width: number;
    height: number;
    obstacles?: Rectangle[];
    exits?: ExitZone[];
    navigableAreas?: NavigationArea[];
    environmentZones?: EnvironmentZone[];
  };
  threat: {
    active: boolean;
    endsAtTick?: number;
    severity?: number;
    immediacy?: number;
    retreatAvailable?: boolean;
    threatenedActorIds?: string[];
  };
  rules?: {
    physics?: PhysicsRules;
    morale?: MoraleRules;
    engagement?: EngagementRules;
  };
  squads?: SquadSpec[];
  objectives?: ObjectiveSpec[];
  terminalConditions?: TerminalConditionSpec[];
  actors: ActorSpec[];
  environment?: EnvironmentSpec;
  scheduledEvents?: ScheduledEventSpec[];
}
