#!/usr/bin/env node
import { readFile, writeFile } from "node:fs/promises";

type Schema = {
  $ref?: string;
  const?: unknown;
  enum?: unknown[];
  type?: string;
  properties?: Record<string, Schema>;
  required?: string[];
  items?: Schema;
  $defs?: Record<string, Schema>;
};

const source = new URL("../packages/schema/schema/scenario-1.3.0.schema.json", import.meta.url);
const destination = new URL("../packages/schema/src/scenario-types.generated.ts", import.meta.url);
const schema = JSON.parse(await readFile(source, "utf8")) as Schema;
const names: Record<string, string> = {
  point: "Point",
  rectangle: "Rectangle",
  exitZone: "ExitZone",
  squad: "SquadSpec",
  actor: "ActorSpec",
  physicsRules: "PhysicsRules",
  moraleRules: "MoraleRules",
  objective: "ObjectiveSpec",
  terminalCondition: "TerminalConditionSpec",
  navigationArea: "NavigationArea",
  environmentZone: "EnvironmentZone",
  environment: "EnvironmentSpec",
  scheduledEvent: "ScheduledEventSpec",
  abstractTool: "AbstractToolSpec",
  engagementRules: "EngagementRules",
};

function typeFor(value: Schema, indent = ""): string {
  if (value.$ref) return names[value.$ref.split("/").at(-1)!] ?? "string";
  if (value.const !== undefined) return JSON.stringify(value.const);
  if (value.enum) return value.enum.map(item => JSON.stringify(item)).join(" | ");
  if (value.type === "array") return `${typeFor(value.items!)}[]`;
  if (value.type === "object") {
    const required = new Set(value.required ?? []);
    const fields = Object.entries(value.properties ?? {}).map(([key, property]) =>
      `${indent}  ${key}${required.has(key) ? "" : "?"}: ${typeFor(property, `${indent}  `)};`);
    return `{\n${fields.join("\n")}\n${indent}}`;
  }
  return value.type === "integer" ? "number" : value.type ?? "unknown";
}

function interfaceFor(name: string, value: Schema): string {
  const required = new Set(value.required ?? []);
  const fields = Object.entries(value.properties ?? {}).map(([key, property]) =>
    `  ${key}${required.has(key) ? "" : "?"}: ${typeFor(property, "  ")};`);
  return `export interface ${name} {\n${fields.join("\n")}\n}`;
}

const version = schema.properties?.schemaVersion?.const;
if (typeof version !== "string") throw new Error("scenario schema must define a string schemaVersion const");

const output = [
  "// Generated by scripts/generate-schema-types.ts from scenario-1.3.0.schema.json.",
  "// Do not edit this file directly.",
  `export const SCHEMA_VERSION = ${JSON.stringify(version)} as const;`,
  "",
  interfaceFor("Point", schema.$defs!.point!),
  "",
  interfaceFor("Rectangle", schema.$defs!.rectangle!),
  "",
  interfaceFor("ExitZone", schema.$defs!.exitZone!),
  "",
  interfaceFor("SquadSpec", schema.$defs!.squad!),
  "",
  interfaceFor("ActorSpec", schema.$defs!.actor!),
  "",
  interfaceFor("PhysicsRules", schema.$defs!.physicsRules!),
  "",
  interfaceFor("MoraleRules", schema.$defs!.moraleRules!),
  "",
  interfaceFor("ObjectiveSpec", schema.$defs!.objective!),
  "",
  interfaceFor("TerminalConditionSpec", schema.$defs!.terminalCondition!),
  "",
  interfaceFor("NavigationArea", schema.$defs!.navigationArea!),
  "",
  interfaceFor("EnvironmentZone", schema.$defs!.environmentZone!),
  "",
  interfaceFor("EnvironmentSpec", schema.$defs!.environment!),
  "",
  interfaceFor("ScheduledEventSpec", schema.$defs!.scheduledEvent!),
  "",
  interfaceFor("AbstractToolSpec", schema.$defs!.abstractTool!),
  "",
  interfaceFor("EngagementRules", schema.$defs!.engagementRules!),
  "",
  interfaceFor("ScenarioSpec", schema),
  "",
].join("\n");

if (process.argv.includes("--check")) {
  const existing = await readFile(destination, "utf8").catch(() => "");
  if (existing !== output) {
    console.error("Generated scenario types are out of date. Run npm run schema:generate.");
    process.exitCode = 1;
  }
} else {
  await writeFile(destination, output);
  console.log("Generated packages/schema/src/scenario-types.generated.ts");
}
